class Student:
    
    class_year = 2024
    num_student = 0
    
    def __init__(self,name,age):
        self.name = name
        self.age = age
        Student.num_student += 1
        
student1 = Student("prince",20)
student2 = Student("Alice",20)
student3 = Student("Bob",20)
student4 = Student("Queen",20)
        
print(f"My graduating class  of {Student.class_year} Has {Student.num_student} students")
print(student1.name)
print(student2.name)
print(student3.name)
print(student4.name)